spring:
    application:
        name: TestFramework
    jackson:
        serialization.write_dates_as_timestamps: false
server:
    port: 8080
    address: localhost

proxy:
    zuora:
        servlet_url: /v1/*
        target_url: https://app-0.stg.eu.zuora.com/apps/v1
